INSERT INTO "PUBLIC"."STUDENT"("ID","DATE_OF_BIRTH","STUDENT_CODE","STUDENT_NAME")VALUES(1,to_Date('21-10-1995','dd-MM-yyyy'),'S1','Student 1');
INSERT INTO "PUBLIC"."STUDENT"("ID","DATE_OF_BIRTH","STUDENT_CODE","STUDENT_NAME")VALUES(2,to_Date('20-01-1998','dd-MM-yyyy'),'S2','Student 2');
INSERT INTO "PUBLIC"."STUDENT"("ID","DATE_OF_BIRTH","STUDENT_CODE","STUDENT_NAME")VALUES(3,to_Date('04-04-2000','dd-MM-yyyy'),'S3','Student 3');
INSERT INTO "PUBLIC"."STUDENT"("ID","DATE_OF_BIRTH","STUDENT_CODE","STUDENT_NAME")VALUES(4,to_Date('15-08-1994','dd-MM-yyyy'),'S4','Student 4');
